#!/usr/bin/env bash

if [ ! -d "environ" ]; then
    virtualenv environ --system-site-packages -p /usr/bin/python3.6
fi

ln -sf environ/bin/activate

. ./activate

pip install --upgrade setuptools
pip install --upgrade -r requirements.pip --no-cache-dir

#cd environ/lib/python3.6/
#rm -rf site-packages
#ln -s dist-packages site-packages
